import funciones as fn
print("Bienvenidos a calculadora online")
num1 = int(input("Ingrese el primer numero: "))
num2 = int(input("Ingrese el segundo numero: "))
resultadoSuma = fn.suma(num1,num2)
resultadoResta = fn.resta(num1,num2)
resultadoMulti = fn.multi(num1,num2)
resultadoDivi = fn.division(num1,num2)
resultadoResto = fn.resto(num1,num2)
print(f"el resultado de su suma es :{resultadoSuma}")
print(f"el resultado de su resta es :{resultadoResta}")
print(f"el resultado de su multiplicacion es :{resultadoMulti}")
print(f"el resultado de su division es :{resultadoDivi}")
print(f"el resultado de su resto es :{resultadoResto}")